[template]
exclude = ["create-project-example.svg"]

[placeholders.aws_region]
type = "string"
prompt = "AWS_REGION"
choices = ["us-east-1", "us-east-2", "us-west-1", "us-west-2", "ca-central-1", "eu-west-1", "eu-west-2", "eu-west-3", "eu-west-1", "eu-central-1", "eu-south-1", "ap-south-1", "ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-southeast-1", "ap-southeast-2", "ap-east-1", "sa-east-1", "cn-north-1", "cn-west-1","me-south-1", "af-south-1"]
default = "us-east-1"

[placeholders.aws_account_id]
type = "string"
prompt = "AWS_ACCOUNT_ID"
default = "warning-no-account-id"

[placeholders.aws_tags]
type = "string"
prompt = "aws_tags"
default = 'generatedBy=\"rust-aws-lambda-template\"'