AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: cloudformation stack for {{project-name}} function and sqs queue

Parameters:
  FunctionName:
    Type: String
    Description: Visible name of lambda function, as it will appear in cli & aws console

Resources:
  CustomListFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref FunctionName
      Handler: 'n/a'
      Runtime: provided
      # notice this is the location of your zipped executable
      # that you renamed'bootstrap' (see README)
      CodeUri: ./lambda.zip
      # memory size is in MB
      MemorySize: 1024
      Timeout: 30
      Role: !GetAtt ServiceRole.Arn
      # Events:
      #   Dequeue:
      #     Type: SQS
      #     Properties:
      #       Queue: !GetAtt SomeQueue.Arn
      #       # NOTE: 10 is currently AWS' max value for this.
      #       BatchSize: 1
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess'
        #- 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
        #- 'arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole'
        #- 'arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess'